[package]
name = "Rust-Pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.1"
nalgebra = "0.29.0"
glam = { version = "0.20.0", features = ["mint"] }
rand = "0.8.4"
